// Operation dispatcher — the single entry point for state mutation
// in the journal-based pipeline.
//
// 2026-05-26 (Arch 2 Phase 2). Routes operations by kind:
//   USER      — apply + verifyIntegrity + history.append + journal.append + autosave
//   SYSTEM    — apply + verifyIntegrity + journal.append + autosave (NO undo)
//   TRANSIENT — apply only (NO journal, NO undo, NO autosave)
//
// MANDATORY contracts:
//   - C2 (op purity): apply() handlers do not call crypto.randomUUID().
//     IDs are pre-generated by callers.
//   - C8 (ID exposure): entity refs in payloads use ifcGlobalId in exports/
//     persistence/journals; internal `id` for runtime addressing.
//   - Arch 9 (integrity): user/system ops verify integrity post-apply.

import { OP_KIND, buildOp, withInverse, isValidOpKind } from './types.js'
import { OPERATIONS } from './registry.js'
import { verifyIntegrity } from '../schema/integrity.js'

// Custom error class for dispatch failures — easier to catch in tests +
// future error UI.
export class OperationError extends Error {
  constructor(message, details = {}) {
    super(message)
    this.name = 'OperationError'
    this.details = details
  }
}

// Module-scope transaction state. When inside `transaction(label, fn)`,
// USER-kind ops accumulate here instead of being individually journaled
// and autosaved. On commit, the entire batch journals as one composite
// op (TRANSACTION) and triggers one autosave.
let _activeTransaction = null

// ── Main dispatch entry point ───────────────────────────────────────────────
//
// dispatch(op, sideEffects?) → applied operation (with inverse captured)
//
// `sideEffects` is an injection object that the host (store.js) provides
// at wire-up time. Pulled out as a parameter so dispatch.js stays
// host-agnostic + testable in isolation.
//
//   sideEffects = {
//     getState:        () => state,
//     setState:        (nextState) => void,
//     appendHistory:   (op, inverseOp) => void,
//     appendJournal:   (op, inverseOp) => void,    // Arch 5
//     markAutosaveDirty: () => void,               // Arch 5
//   }
//
// In tests, pass a minimal mock. In the live store, the host wires real impls.
export function dispatch(op, sideEffects) {
  if (!op || typeof op !== 'object') {
    throw new OperationError('dispatch: op must be an object', { op })
  }
  if (!isValidOpKind(op.kind)) {
    throw new OperationError(`dispatch: invalid op.kind "${op.kind}"`, { op })
  }
  const def = OPERATIONS[op.type]
  if (!def) {
    throw new OperationError(`dispatch: unknown op.type "${op.type}"`, { op })
  }
  // Compile-time kind contract: registry's declared kind must match the
  // operation's kind. Mismatch usually means the caller hand-rolled an op
  // instead of using buildOp + the registry default.
  if (def.kind !== op.kind) {
    throw new OperationError(
      `dispatch: op.kind "${op.kind}" doesn't match registry kind "${def.kind}" for type "${op.type}"`,
      { op, registryKind: def.kind },
    )
  }
  if (!sideEffects || typeof sideEffects.getState !== 'function') {
    throw new OperationError('dispatch: sideEffects.getState is required', { op })
  }

  const currentState = sideEffects.getState()
  // Apply — pure transformation. apply() returns { nextState, inverse }.
  let applied
  try {
    applied = def.apply(currentState, op.payload ?? {})
  } catch (err) {
    throw new OperationError(`dispatch: apply threw for "${op.type}": ${err.message}`, { op, cause: err })
  }
  const { nextState, inverse } = applied ?? {}
  if (!nextState) {
    throw new OperationError(`dispatch: apply returned no nextState for "${op.type}"`, { op })
  }

  // Integrity verification — user + system ops only. Skip for transient
  // (selection / hover / drag are too frequent and don't mutate model
  // entities — they touch view-only fields).
  if (op.kind !== OP_KIND.TRANSIENT) {
    const ir = verifyIntegrity(nextState)
    if (!ir.valid) {
      throw new OperationError(
        `dispatch: op "${op.type}" produced state failing integrity: ${ir.count} issue(s); first: ${ir.issues[0]?.message}`,
        { op, integrity: ir },
      )
    }
  }

  // TRANSIENT ops inside a transaction are forbidden — selection/hover/
  // drag state can't roll back coherently with model changes. Reject
  // immediately so the assertion is loud at the offending dispatch site.
  if (_activeTransaction && op.kind === OP_KIND.TRANSIENT) {
    throw new OperationError(
      `transaction: TRANSIENT op "${op.type}" inside transaction "${_activeTransaction.label}" is forbidden`,
      { op, transaction: _activeTransaction.label },
    )
  }

  // Stamp the inverse onto the op for journal storage.
  const sealed = inverse ? withInverse(op, inverse) : op

  // Commit state to the store.
  sideEffects.setState(nextState)

  // Route by kind (C1).
  switch (op.kind) {
    case OP_KIND.USER: {
      // Inside a transaction, accumulate; flush on commit.
      if (_activeTransaction) {
        _activeTransaction.ops.push(sealed)
      } else {
        sideEffects.appendHistory?.(sealed, inverse)
        sideEffects.appendJournal?.(sealed, inverse)
        sideEffects.markAutosaveDirty?.()
      }
      break
    }
    case OP_KIND.SYSTEM: {
      // System ops never enter the undo stack but DO journal for audit.
      sideEffects.appendJournal?.(sealed, inverse)
      sideEffects.markAutosaveDirty?.()
      break
    }
    case OP_KIND.TRANSIENT: {
      // Pure view-state. Nothing persisted.
      break
    }
  }

  return sealed
}

// ── Transactions ────────────────────────────────────────────────────────────
//
// transaction(label, fn) groups multiple USER ops under one undo step.
// Transient ops are forbidden inside transactions (would corrupt undo
// semantics — selection state can't roll back coherently with model
// changes).
//
//   transaction('addRoom', () => {
//     dispatch(addWall1)
//     dispatch(addWall2)
//     dispatch(saveRoom)
//   })

export function transaction(label, fn, sideEffects) {
  if (_activeTransaction) {
    throw new OperationError('transaction: nested transactions not supported')
  }
  if (typeof label !== 'string' || !label) {
    throw new OperationError('transaction: label required')
  }
  if (typeof fn !== 'function') {
    throw new OperationError('transaction: body must be a function')
  }
  _activeTransaction = { label, ops: [], startedAt: Date.now() }
  let result
  try {
    result = fn()
  } catch (err) {
    // Abort: leave ops applied (the state was mutated as each ran). A
    // future enhancement could rollback by replaying inverses, but for now
    // surface the error and leave the partial state. Transient-rejection
    // throws bubble through here too.
    _activeTransaction = null
    throw err
  }
  const tx = _activeTransaction
  _activeTransaction = null

  // Commit: emit a single composite op carrying the children.
  if (tx.ops.length > 0 && sideEffects) {
    const composite = {
      id:            tx.ops[0].id + '__tx',
      type:          'TRANSACTION',
      kind:          OP_KIND.USER,
      schemaVersion: tx.ops[0].schemaVersion,
      payload:       { label: tx.label, children: tx.ops.map(o => o.id) },
      inverse:       { type: '__TX_INVERSE__', payload: { children: tx.ops.map(c => c.inverse).filter(Boolean).reverse() } },
      timestamp:     tx.startedAt,
      author:        tx.ops[0].author,
    }
    sideEffects.appendHistory?.(composite, composite.inverse)
    sideEffects.appendJournal?.(composite, composite.inverse)
    sideEffects.markAutosaveDirty?.()
  }
  return result
}

// Test/internal helper — surfaces the active transaction state for asserts.
export function _inspectTransactionState() {
  return _activeTransaction ? { ..._activeTransaction } : null
}
