// Operation type definitions — single source of truth for the
// dispatch-based mutation pipeline (Arch 2 Phase 2).
//
// Every state-changing action in the app is modelled as an Operation:
// a pure data object describing the intent. The dispatcher applies it,
// captures the inverse, and routes it through history / journal /
// autosave based on its `kind`.
//
// Correction 1 (C1): kind discriminates routing semantics.
// Correction 2 (C2): IDs are generated BEFORE dispatch — never inside
//                    apply(). Enforced by scripts/verify-op-purity.mjs.

import { SCHEMA_VERSION } from './_schemaVersion.js'

// ── Operation kinds ─────────────────────────────────────────────────────────

export const OP_KIND = Object.freeze({
  // User-initiated, deliberate state change. Full pipeline:
  //   apply → integrity check → history.append → journal.append → autosave.markDirty
  // Examples: ADD_WALL, DELETE_WALL, SET_WALL_MATERIAL, ADD_OPENING,
  // SET_ROOM_TYPE, all structural slice setters, all MEP entity setters.
  USER: 'user',

  // System-initiated, deterministic, NOT subject to undo. Pipeline:
  //   apply → integrity check → journal.append → autosave.markDirty
  // Examples: MIGRATE_SCHEMA_VERSION (Arch 5), REPAIR_BROKEN_REFERENCE
  // (Arch 9 repair path), BACKFILL_IFC_GLOBAL_ID, NORMALIZE_LEGACY_ALIAS,
  // CATALOG_VERSION_STAMP, MIGRATE_LEGACY_LOCALSTORAGE.
  // Appear in audit log but never in the user-visible undo stack.
  SYSTEM: 'system',

  // In-memory, view-only changes. NO journal, NO undo, NO autosave,
  // NO expensive compute invalidation. Pipeline:
  //   apply → store.set
  // Examples: SET_SELECTED_WALL_ID, SET_HOVERED_ENTITY, SET_DRAG_PREVIEW,
  // SET_SNAP_HINT, SET_MEASUREMENT_PREVIEW, SET_LAYER_VISIBILITY,
  // SET_CURRENT_FLOOR_ID, SET_DRAFT_OPENING.
  // Transient ops are forbidden inside transaction() (asserted at runtime).
  TRANSIENT: 'transient',
})

// Helper: ordered list for iteration / UI dropdowns.
export const OP_KINDS_ORDERED = Object.freeze([OP_KIND.USER, OP_KIND.SYSTEM, OP_KIND.TRANSIENT])

export function isValidOpKind(kind) {
  return kind === OP_KIND.USER || kind === OP_KIND.SYSTEM || kind === OP_KIND.TRANSIENT
}

// ── Operation shape ─────────────────────────────────────────────────────────
//
// {
//   id:            string,           // pre-generated by caller (C2)
//   type:          string,           // 'ADD_WALL' | 'MOVE_NODE' | ...
//   kind:          OP_KIND.*,        // see above
//   schemaVersion: number,           // SCHEMA_VERSION at dispatch time
//   payload:       object,           // type-specific; entity refs via
//                                    // ifcGlobalId where exposed (C8)
//   inverse:       object | null,    // captured at apply time; null = irreversible
//   timestamp:     number,           // Date.now() at dispatch
//   author:        string,           // user id / 'system' / 'migration'
// }

// ── Operation source labels ─────────────────────────────────────────────────
// `author` field values. Mostly informational — used by the audit log and
// future collaboration features.

export const OP_AUTHOR = Object.freeze({
  USER:       'user',         // default; overridden by collab when present
  SYSTEM:     'system',       // system-kind ops (migrations, repairs)
  MIGRATION:  'migration',    // Arch 5 schema upgrades
  TEST:       'test',         // verify scripts + integration tests
})

// ── Constructors ────────────────────────────────────────────────────────────
// Build a well-formed Operation object. Callers MUST pre-generate any IDs
// in the payload (C2). The constructor stamps the operation envelope.

export function buildOp({ id, type, kind, payload, author }) {
  if (!id) throw new TypeError('buildOp: id is required (pre-generate via uid())')
  if (!type) throw new TypeError('buildOp: type is required')
  if (!isValidOpKind(kind)) throw new TypeError(`buildOp: invalid kind "${kind}"`)
  return Object.freeze({
    id,
    type,
    kind,
    schemaVersion: SCHEMA_VERSION,
    payload:       payload ?? {},
    inverse:       null,                              // set by dispatch.apply()
    timestamp:     Date.now(),
    author:        author ?? OP_AUTHOR.USER,
  })
}

// Mark an operation as inverse-captured. Returns a new frozen object
// (operations stay immutable).
export function withInverse(op, inverse) {
  return Object.freeze({ ...op, inverse })
}
